In [84]:
import pandas as pd
import numpy as np
from pathlib import Path

In [85]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.float_format", "{:.2f}".format)

# Loading the tables

## Joining survey with train service

In [86]:
#service = pd.read_parquet("Data/service_operational_kpis.parquet")

In [87]:
#service.head()

In [88]:
#service.shape

In [89]:
#survey_data = pd.read_parquet("Tables/survey_cleaned.parquet")

In [90]:
#survey_data['metadata_departure_date'] = pd.to_datetime(survey_data['metadata_departure_date']).dt.strftime('%Y%m%d')
#survey_data['service_id'] = survey_data['metadata_train_number'].astype(int).astype(str) + '_' + survey_data['metadata_departure_date']
#df = pd.merge(survey_data, service, on='service_id', how='inner')

In [91]:
df = pd.read_parquet("Data/survey_and_operational_data.parquet")

In [92]:
df.shape

(178833, 211)

In [93]:
df.head()

,metadata_booking_date,metadata_class_of_service,metadata_class_of_service_code,metadata_coach_number,metadata_compensation_flag,metadata_currency,metadata_delay_code,metadata_delay_at_arrival,metadata_departure_date,metadata_departure_hour,metadata_destination_station,metadata_destination_station_code,metadata_disrup,metadata_origin_station,metadata_origin_station_code,metadata_price,metadata_on_board_the_train_v,metadata_overall_experience_v,metadata_q14_op,metadata_q17_op,metadata_recommendation_nps_a,metadata_assistance_service_v,metadata_q_total_duration,metadata_route,metadata_route_code,metadata_seat_number,metadata_segment,metadata_segment_code,metadata_tier_level,metadata_tier_level_code,metadata_train_number,metadata_train_type,metadata_train_type_code,metadata_trips_l12_months,metadata_end_date,metadata_start_date,question_overall_satisfaction_booking_experience,question_overall_satisfaction_wifi_onboard_the_train,question_overall_satisfaction_experience_at_departure_station,question_overall_satisfaction_journey_punctuality,question_overall_satisfaction_comfort_onboard_the_train,question_overall_satisfaction_cleanliness_onboard_the_train,question_overall_satisfaction_overall_service_from_eurostar_staff,question_overall_satisfaction_information_provided_to_you_before_travelling,question_lounge_overall_f_b_your_overall_experience_in_the_premier_lounge,question_lounge_overall_f_b_the_beverage_offering_in_the_lounge,question_lounge_overall_f_b_available_space_seating,question_lounge_overall_f_b_lounge_staff,question_lounge_overall_f_b_cocktail_bar,question_lounge_overall_f_b_newspapers_magazines,question_lounge_overall_f_b_your_welcome_arrival_at_the_lounge,question_lounge_overall_f_b_atmosphere_ambience_in_the_lounge,question_lounge_overall_f_b_furniture_and_d_cor_in_the_lounge,question_lounge_overall_f_b_information_regarding_your_train_departure,question_lounge_overall_f_b_cleanliness_of_the_lounge,question_lounge_overall_f_b_the_food_offering_in_the_lounge,question_lounge_improvement,question_onboard_catering_met_quality_of_food_in_meal_service,question_onboard_catering_met_receiving_preferred_meal_option,question_onboard_catering_met_quality_of_beverages_in_meal_service,question_onboard_catering_met_staff_hospitality_during_meal_service,question_onboard_catering_met_portion_sizes,question_onboard_catering_met_range_of_food_available_in_meal_service,question_onboard_catering_met_range_of_drinks_available_in_meal_service,question_onboard_catering_met_presentation_of_food,question_disruption_performan_the_information_available_to_you,question_disruption_performan_the_compensation_you_received_as_a_result_of_this_disruption,question_disruption_performan_frequency_regularity_of_updates,question_disruption_performan_the_accuracy_of_all_information_provided,question_disruption_performan_the_consistency_of_information_from_different_sources,question_disruption_performan_the_frequency_with_which_you_were_kept_updated,question_disruption_performan_information_provided_in_stations_e_g_from_staff_on_screens,question_disruption_performan_information_on_board_the_train_e_g_from_staff_announcements,question_disruption_performan_information_available_through_the_eurostar_website_or_app,question_disruption_performan_information_received_from_eurostar_via_e_mail_or_sms,question_disruption_performan_passenger_care_hotel_taxi_food_boxes,question_disruption_performan_eurostar_s_overall_management_of_this_disruption,question_usage_hv,question_disability_and_acces,question_assistance_service,question_assistance_service_r,question_language,question_at_the_station_checking_in_to_departures_area,question_at_the_station_boarding_the_train,question_at_the_station_toilets_washrooms_in_the_station,question_at_the_station_the_security_process_baggage_checks_and_scanners,question_at_the_station_passport_control,question_at_the_station_pre_departure_announcements_in_the_station,question_at_the_station_available_space_seating_in_the_waiting_area,question_at_the_station_the_facilities_in_the_waiting_area,question_at_the_station_the_signage_and_directions_to_your_platform_and_train,question_on_board_the_train1_the_noise_on_board,question_on_board_the_train1_the_atmosphere_on_board,question_on_board_the_train1_the_temperature_on_board,question_on_board_the_train1_the_level_of_comfort_on_board,question_on_board_the_train1_the_availability_of_toilet_facilities_on_board,question_on_board_the_train1_the_cleanliness_on_board_the_train,question_on_board_the_train1_seat_comfort,question_arrival_the_goodbye_you_received_from_train_staff_when_you_reached_your_destination,question_arrival_disembarking_the_train,question_arrival_signage_for_onward_journey_and_or_connections_at_destination_station,question_arrival_onboard_announcement_on_arrival_by_train_manager,question_staff_on_board_cleaning_staff,question_staff_on_board_train_manager,question_service_provided_by_when_getting_in_touch_via_the_contact_centre,question_service_provided_by_at_the_departure_station,question_service_provided_by_at_the_ticket_gates,question_service_provided_by_at_security_baggage_checks_scanning,question_service_provided_by_on_the_train,question_service_provided_by_train_manager,question_service_provided_by_at_the_eurostar_caf_onboard,question_service_provided_by_at_your_destination_station,question_staff_manners_staff_were_visible,question_staff_manners_staff_were_friendly_and_welcoming,question_staff_manners_staff_were_helpful,question_impact_of_cleaning_p_this_cleaning_process_is_important_to_ensure_your_comfort_on_the_train,question_impact_of_cleaning_p_this_cleaning_process_helps_to_reinforce_your_satisfaction_with_eurostar,question_impact_of_cleaning_p_this_cleaning_process_encourages_you_to_choose_eurostar_again_in_the_future,question_ticket_price_satisfa,question_overall_rating,question_reasons_for_choosing,question_future_consideration,question_strategic_pillar_ass_travelling_by_eurostar_is_an_environmentally_sustainable_option,question_strategic_pillar_ass_eurostar_manages_its_food_and_drink_offering_at_station_lounges_and_onboard_in_an_environmentally_sustainable_way,question_lounge_usage,question_hv_11,question_hv_12,question_hv_22,question_hv_21,question_hv_32,question_hv_31,question_hv_42,question_hv_41,question_residence,question_age,question_on_board_the_train2_the_cleanliness_of_toilet_facilities_on_board_the_train,question_on_board_the_train2_the_information_and_announcements_provided_on_board,question_on_board_the_train2_range_of_food_drink_available_at_the_eurostar_caf,question_on_board_the_train2_the_wi_fi_on_board,question_qid61_nps_group,question_onboard_catering_ove,question_visit_cafe,question_eurostar_cafe_your_overall_experience_at_the_eurostar_caf,question_eurostar_cafe_the_service_you_received_from_staff,question_eurostar_cafe_the_quality_of_the_food,question_eurostar_cafe_the_quality_of_the_drinks,question_eurostar_cafe_the_range_of_food_on_offer,question_eurostar_cafe_the_range_of_drinks_on_offer,question_eurostar_cafe_the_prices_value_for_money_of_food_and_drinks,question_eurostar_cafe_the_product_availabilty,question_purchase_cafe,question_connecting_journey,question_main_trip_purpose,question_leisure_reason,service_id,trainset,equipment_type,train_service,route_type,origin_theoretical_time,destination_theoretical_time,restriction_open_Toilets,restriction_open_Air Conditioning,restriction_open_Refrigeration,restriction_open_Windows,restriction_open_WiFi,restriction_open_Heating,total restrictions,restriction_days_Toilets,restriction_days_Air Conditioning,restriction_days_Refrigeration,restriction_days_Windows,restriction_days_WiFi,restriction_days_Heating,longest restriction,pm_days_since_catering,pm_days_since_toilet,pm_days_since_climate,pm_days_since_interior,pm_days_since_reliability,pm_days_since_comms,pm_days_since_wifi,average days since last exams,pm_has_prior_catering,pm_has_prior_toilet,pm_has_prior_climate,pm_has_prior_interior,pm_has_prior_reliability,pm_has_prior_comms,pm_has_prior_wifi,cm_open_climate,cm_open_wifi,cm_open_interior,cm_open_catering,cm_open_toilet,cm_open_cleaning,total open faults,clean_score_routine,clean_hours_since_routine,clean_score_deep,clean_days_since_deep,last_clean_score,hours_since_last_clean,clean_has_prior_routine,clean_has_prior_deep,n_trainsets,early_journey_delay_minute,arrival_delay_minute,compensation_liability_evouchers,compensation_liability_cash,delay_cause_id
0,2024-10-01T14:58:17Z,Eurostar Standard,1.00,12.00,0.00,EUR,2.00,1.00,20250101,18:04,Amsterdam Centraal,5.00,None,London St Pancras Int'l,21.00,144.00,None,None,None,None,8.00,None,209,Blue,1.00,33.00,Small Business,6.00,Classique,3.00,9152.00,E320,2.00,1.00,2025-01-02T15:05:35Z,2025-01-02T15:02:05Z,5,2,4,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,5,<NA>,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,4,<NA>,<NA>,<NA>,4,5,['It was the most environmentally-friendly opt...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,3,Range of food/drink available at the Eurostar ...,<NA>,None,<NA>,None,United Kingdom,Between 26 - 34,4,4,3,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9152_20250101,4009+4010,E320,9152,Channel,2025-01-01 18:04:00+00:00,2025-01-01 23:20:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.00,26.00,26.00,128.00,232.00,2695.00,NaN,529.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,95.83,0.33,NaN,NaN,95.83,0.33,1,0,2,2.00,1.00,0.00,0.00,NaN
1,2024-11-22T06:45:54Z,Eurostar Standard,1.00,2.00,0.00,GBP,2.00,7.00,20250101,12:56,London St Pancras Int'l,21.00,None,Brussels Midi / Zuid,9.00,115.00,None,Wifi was not working,None,None,10.00,None,201,Blue,1.00,65.00,None,NaN,Classique,3.00,9135.00,E300,1.00,1.00,2025-01-02T15:05:37Z,2025-01-02T15:02:15Z,5,1,5,4,4,4,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,3,<NA>,4,4,4,<NA>,<NA>,<NA>,<NA>,5,5,5,<NA>,<NA>,<NA>,5,5,['It was the cheapest option' 'It was the quic...,Eurostar would be my preferred choice,<NA>,<NA>,None,None,<NA>,<NA>,None,<NA>,None,4,At security (baggage checks/scanning),United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a main holiday,9135_20250101,3221+3222,E300,9135,Channel,2025-01-01 12:56:00+00:00,2025-01-01 13:57:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.00,3623.00,212.00,293.00,171.00,1904.00,NaN,1047.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,9.00,7.00,0.00,0.00,14.00
2,2024-12-26T03:54:23Z,Eurostar Standard,1.00,10.00,0.00,EUR,2.00,2.00,20250101,19:34,Brussels Midi / Zuid,9.00,None,London St Pancras Int'l,21.00,134.00,None,The departing gate in London was very crowded ...,None,None,9.00,None,175,Blue,1.00,11.00,Small Business,6.00,Classique,3.00,9158.00,E320,2.00,2.00,2025-01-02T15:07:01Z,2025-01-02T15:04:05Z,5,4,2,5,5,4,4,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,4,<NA>,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,5,['It was the quickest option'\n 'It was the mo...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,<NA>,The availability of toilet facilities on board,<NA>,None,<NA>,None,Belgium,Between 26 - 34,4,4,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9158_20250101,4033+4034,E320,9158,Channel,2025-01-01 19:34:00+00:00,2025-01-01 22:35:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.00,50.00,37.00,5.00,202.00,NaN,NaN,68.60,1,1,1,1,1,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,3.00,2.00,0.00,0.00,NaN
3,2024-12-29T15:45:51Z,Eurostar Premier,3.00,11.00,0.00,EUR,2.00,14.00,20250101,19:10,Paris Gare du Nord,25.00,None,Amsterdam Centraal,5.00,132.00,None,"none, it was all good",None,None,10.00,None,204,Red,2.00,74.00,None,NaN,None,NaN,9388.00,TGH,6.00,1.00,2025-01-02T15:07:04Z,2025-01-02T15:03:39Z,5,<NA>,5,5,5,4,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,4,5,5,5,4,3,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Did you use the Eurostar Lounge at ${e://Field...,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,5,<NA>,5,5,5,5,5,['It was the quickest option'\n 'To avoid addi...,Eurostar would be my preferred choice,5,3,No,None,<NA>,<NA>,None,5,Disembarking the train,<NA>,None,France,Between 18 - 25,<NA>,<NA>,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9388_20250101,4343,TGH,9388,Continental,2025-01-01 19:10:00+00:00,2025-01-01 22:40:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,NaN,89.00,50.50,0,0,0,0,1,0,1,5.00,0.00,6.00,15.00,6.00,2.00,34.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,5.00,14.00,0.00,0.00,14.00
4,2024-07-24T14:45:14Z,Eurostar Standard,1.00,12.00,0.00,GBP,2.00,1.00,20250101,14:42,London St Pancras Int'l,21.00,None,Paris Gare du Nord,25.00,54.00,None,I thought the facilities were great at Paris G...,None,None,8.00,None,309,Blue,1.00,33.00,None,NaN,Classique,3.00,9037.00,E320,2.00,2.00,2025-01-02T15:07:25Z,2025-01-02T15:02:15Z,4,3,5,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,4,4,<NA>,<NA>,<NA>,5,5,['It was the most environmentally-friendly opt...,Eurostar would be my preferred choice,5,<NA>,None,None,<NA>,<NA>,None,3,Signage for onward journey and/or connections ...,<NA>,None,United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a short break,9037_20250101,4021+4022,E320,9037,Channel,2025-01-01 14:42:00+00:00,2025-01-01 16:00:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.00,32.00,6.00,85.00,257.00,2793.00,NaN,538.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,4.00,1.00,0.00,0.00,NaN

## Merging precise Arrival & Departure Delay data

In [94]:
# Load precise delay files
arr_delay = pd.read_csv('Data/Arrival delay.csv')
dep_delay = pd.read_csv('Data/Departure delay.csv')

# Drop last 3 footer rows (Total, NaN, Applied Filters)
arr_delay = arr_delay.drop(arr_delay.tail(3).index)
dep_delay = dep_delay.drop(dep_delay.tail(3).index)

# Correct London timezone bug: St-Pancras arrivals and departures are recorded 60 min too early
arr_delay.loc[arr_delay['Destination Station Name'] == 'St-Pancras-International', 'Arrival Delay (Minutes)'] += 60
dep_delay.loc[dep_delay['Origin Station Name'] == 'St-Pancras-International', 'Departure Delay (Minutes)'] += 60

# Parse date columns (format is dd/mm/yyyy) and build service_id: movementnumber_yyyymmdd
arr_delay['Departure Date'] = pd.to_datetime(arr_delay['Departure Date'], dayfirst=True)
dep_delay['Departure Date'] = pd.to_datetime(dep_delay['Departure Date'], dayfirst=True)

arr_delay['service_id'] = arr_delay['Movement Number'].astype(str) + '_' + arr_delay['Departure Date'].dt.strftime('%Y%m%d')
dep_delay['service_id'] = dep_delay['Movement Number'].astype(str) + '_' + dep_delay['Departure Date'].dt.strftime('%Y%m%d')

print(f'Arrival delay total rows: {len(arr_delay)}')
print(f'Departure delay total rows: {len(dep_delay)}')

Arrival delay total rows: 46259
Departure delay total rows: 52867

In [95]:
def concat_vals(s):
    vals = s.dropna().astype(str).unique()
    return ' | '.join(vals) if len(vals) > 0 else None

cause_cols = ['Cause Category', 'Cause Domain', 'Cause Responsibility']

# For each file: keep first value for all columns, concatenate cause columns across duplicates
arr_agg = {col: 'first' for col in arr_delay.columns if col not in cause_cols + ['service_id']}
arr_agg.update({col: concat_vals for col in cause_cols})
arr_delay = arr_delay.groupby('service_id', sort=False).agg(arr_agg).reset_index()

dep_agg = {col: 'first' for col in dep_delay.columns if col not in cause_cols + ['service_id']}
dep_agg.update({col: concat_vals for col in cause_cols})
dep_delay = dep_delay.groupby('service_id', sort=False).agg(dep_agg).reset_index()

In [96]:
# Left join to keep all services, including those with no recorded delay
df = df.merge(arr_delay, on='service_id', how='left')
df = df.merge(dep_delay, on='service_id', how='left')

print(f'df shape after merging precise delay data: {df.shape}')

df shape after merging precise delay data: (178833, 232)

## Merging Rotations data

In [97]:
# Load rotations file
rotations = pd.read_csv('Data/Rotations.csv')

# Drop last 3 footer rows
rotations = rotations.drop(rotations.tail(3).index)

# Parse date column (format is dd/mm/yyyy) and build service_id: trainnumber_yyyymmdd
rotations['Travel Date'] = pd.to_datetime(rotations['Travel Date'], dayfirst=True)
rotations['service_id'] = rotations['Train Number'].astype(str) + '_' + rotations['Travel Date'].dt.strftime('%Y%m%d')

# Convert HH:MM:SS to decimal minutes (2 decimal places)
def hms_to_minutes(col):
    parts = col.str.split(':', expand=True).astype(float)
    return (parts[0] * 60 + parts[1] + parts[2] / 60).round(2)

for col in ['Theoretical Rotation Time', 'Effective Rotation Time', 'Exceeded Rotation Time']:
    rotations[col] = hms_to_minutes(rotations[col])

# Deduplicate on service_id
rotations = rotations.drop_duplicates('service_id', keep='first')

# Keep only relevant columns
rotations = rotations[['service_id', 'Rame Number', 'Travel Number',
                         'Theoretical Rotation Time', 'Effective Rotation Time', 'Exceeded Rotation Time']]

In [98]:
df = df.merge(rotations, on='service_id', how='left')

## Merging Fleet Availability data

In [99]:
# Load fleet availability
fleet = pd.read_csv('Data/Fleet availability.csv')
fleet['Date'] = pd.to_datetime(fleet['Date'])

# Group by Date + Grouped Parc, sum departure columns
fleet_agg = (
    fleet
    .groupby(['Date', 'Grouped Parc'], as_index=False)
    .agg(
        met_departures=('Sum of Met departures', 'sum'),
        ordered_departures=('Sum of Ordered departures', 'sum'),
        unmet_departures=('Sum of Unmet departures', 'sum')
    )
)

# Fleet Reliability = met / ordered * 100
fleet_agg['fleet_reliability'] = (
    fleet_agg['met_departures'] / fleet_agg['ordered_departures'] * 100
).round(2)

# Rename Grouped Parc categories
fleet_agg['Grouped Parc'] = fleet_agg['Grouped Parc'].replace({
    'Cross-channel': 'Channel',
    'Continent': 'Continental'
})

# Compute totals per date (Continental + Channel combined)
totals = (
    fleet_agg
    .groupby('Date', as_index=False)
    .agg(
        total_met_departures=('met_departures', 'sum'),
        total_ordered_departures=('ordered_departures', 'sum'),
        total_unmet_departures=('unmet_departures', 'sum')
    )
)
totals['total_fleet_reliability'] = (
    totals['total_met_departures'] / totals['total_ordered_departures'] * 100
).round(2)

# Add total columns back to each row (both Continental and Channel get the same totals)
fleet_agg = fleet_agg.merge(totals, on='Date', how='left')

# Format date as yyyymmdd string to match metadata_departure_date
fleet_agg['metadata_departure_date'] = fleet_agg['Date'].dt.strftime('%Y%m%d')

In [100]:
df = df.merge(
    fleet_agg.rename(columns={'Grouped Parc': 'route_type'}),
    on=['metadata_departure_date', 'route_type'],
    how='left'
)
print(f'df shape after merging fleet availability: {df.shape}')

df shape after merging fleet availability: (178833, 246)

In [101]:
df.head(40)

,metadata_booking_date,metadata_class_of_service,metadata_class_of_service_code,metadata_coach_number,metadata_compensation_flag,metadata_currency,metadata_delay_code,metadata_delay_at_arrival,metadata_departure_date,metadata_departure_hour,metadata_destination_station,metadata_destination_station_code,metadata_disrup,metadata_origin_station,metadata_origin_station_code,metadata_price,metadata_on_board_the_train_v,metadata_overall_experience_v,metadata_q14_op,metadata_q17_op,metadata_recommendation_nps_a,metadata_assistance_service_v,metadata_q_total_duration,metadata_route,metadata_route_code,metadata_seat_number,metadata_segment,metadata_segment_code,metadata_tier_level,metadata_tier_level_code,metadata_train_number,metadata_train_type,metadata_train_type_code,metadata_trips_l12_months,metadata_end_date,metadata_start_date,question_overall_satisfaction_booking_experience,question_overall_satisfaction_wifi_onboard_the_train,question_overall_satisfaction_experience_at_departure_station,question_overall_satisfaction_journey_punctuality,question_overall_satisfaction_comfort_onboard_the_train,question_overall_satisfaction_cleanliness_onboard_the_train,question_overall_satisfaction_overall_service_from_eurostar_staff,question_overall_satisfaction_information_provided_to_you_before_travelling,question_lounge_overall_f_b_your_overall_experience_in_the_premier_lounge,question_lounge_overall_f_b_the_beverage_offering_in_the_lounge,question_lounge_overall_f_b_available_space_seating,question_lounge_overall_f_b_lounge_staff,question_lounge_overall_f_b_cocktail_bar,question_lounge_overall_f_b_newspapers_magazines,question_lounge_overall_f_b_your_welcome_arrival_at_the_lounge,question_lounge_overall_f_b_atmosphere_ambience_in_the_lounge,question_lounge_overall_f_b_furniture_and_d_cor_in_the_lounge,question_lounge_overall_f_b_information_regarding_your_train_departure,question_lounge_overall_f_b_cleanliness_of_the_lounge,question_lounge_overall_f_b_the_food_offering_in_the_lounge,question_lounge_improvement,question_onboard_catering_met_quality_of_food_in_meal_service,question_onboard_catering_met_receiving_preferred_meal_option,question_onboard_catering_met_quality_of_beverages_in_meal_service,question_onboard_catering_met_staff_hospitality_during_meal_service,question_onboard_catering_met_portion_sizes,question_onboard_catering_met_range_of_food_available_in_meal_service,question_onboard_catering_met_range_of_drinks_available_in_meal_service,question_onboard_catering_met_presentation_of_food,question_disruption_performan_the_information_available_to_you,question_disruption_performan_the_compensation_you_received_as_a_result_of_this_disruption,question_disruption_performan_frequency_regularity_of_updates,question_disruption_performan_the_accuracy_of_all_information_provided,question_disruption_performan_the_consistency_of_information_from_different_sources,question_disruption_performan_the_frequency_with_which_you_were_kept_updated,question_disruption_performan_information_provided_in_stations_e_g_from_staff_on_screens,question_disruption_performan_information_on_board_the_train_e_g_from_staff_announcements,question_disruption_performan_information_available_through_the_eurostar_website_or_app,question_disruption_performan_information_received_from_eurostar_via_e_mail_or_sms,question_disruption_performan_passenger_care_hotel_taxi_food_boxes,question_disruption_performan_eurostar_s_overall_management_of_this_disruption,question_usage_hv,question_disability_and_acces,question_assistance_service,question_assistance_service_r,question_language,question_at_the_station_checking_in_to_departures_area,question_at_the_station_boarding_the_train,question_at_the_station_toilets_washrooms_in_the_station,question_at_the_station_the_security_process_baggage_checks_and_scanners,question_at_the_station_passport_control,question_at_the_station_pre_departure_announcements_in_the_station,question_at_the_station_available_space_seating_in_the_waiting_area,question_at_the_station_the_facilities_in_the_waiting_area,question_at_the_station_the_signage_and_directions_to_your_platform_and_train,question_on_board_the_train1_the_noise_on_board,question_on_board_the_train1_the_atmosphere_on_board,question_on_board_the_train1_the_temperature_on_board,question_on_board_the_train1_the_level_of_comfort_on_board,question_on_board_the_train1_the_availability_of_toilet_facilities_on_board,question_on_board_the_train1_the_cleanliness_on_board_the_train,question_on_board_the_train1_seat_comfort,question_arrival_the_goodbye_you_received_from_train_staff_when_you_reached_your_destination,question_arrival_disembarking_the_train,question_arrival_signage_for_onward_journey_and_or_connections_at_destination_station,question_arrival_onboard_announcement_on_arrival_by_train_manager,question_staff_on_board_cleaning_staff,question_staff_on_board_train_manager,question_service_provided_by_when_getting_in_touch_via_the_contact_centre,question_service_provided_by_at_the_departure_station,question_service_provided_by_at_the_ticket_gates,question_service_provided_by_at_security_baggage_checks_scanning,question_service_provided_by_on_the_train,question_service_provided_by_train_manager,question_service_provided_by_at_the_eurostar_caf_onboard,question_service_provided_by_at_your_destination_station,question_staff_manners_staff_were_visible,question_staff_manners_staff_were_friendly_and_welcoming,question_staff_manners_staff_were_helpful,question_impact_of_cleaning_p_this_cleaning_process_is_important_to_ensure_your_comfort_on_the_train,question_impact_of_cleaning_p_this_cleaning_process_helps_to_reinforce_your_satisfaction_with_eurostar,question_impact_of_cleaning_p_this_cleaning_process_encourages_you_to_choose_eurostar_again_in_the_future,question_ticket_price_satisfa,question_overall_rating,question_reasons_for_choosing,question_future_consideration,question_strategic_pillar_ass_travelling_by_eurostar_is_an_environmentally_sustainable_option,question_strategic_pillar_ass_eurostar_manages_its_food_and_drink_offering_at_station_lounges_and_onboard_in_an_environmentally_sustainable_way,question_lounge_usage,question_hv_11,question_hv_12,question_hv_22,question_hv_21,question_hv_32,question_hv_31,question_hv_42,question_hv_41,question_residence,question_age,question_on_board_the_train2_the_cleanliness_of_toilet_facilities_on_board_the_train,question_on_board_the_train2_the_information_and_announcements_provided_on_board,question_on_board_the_train2_range_of_food_drink_available_at_the_eurostar_caf,question_on_board_the_train2_the_wi_fi_on_board,question_qid61_nps_group,question_onboard_catering_ove,question_visit_cafe,question_eurostar_cafe_your_overall_experience_at_the_eurostar_caf,question_eurostar_cafe_the_service_you_received_from_staff,question_eurostar_cafe_the_quality_of_the_food,question_eurostar_cafe_the_quality_of_the_drinks,question_eurostar_cafe_the_range_of_food_on_offer,question_eurostar_cafe_the_range_of_drinks_on_offer,question_eurostar_cafe_the_prices_value_for_money_of_food_and_drinks,question_eurostar_cafe_the_product_availabilty,question_purchase_cafe,question_connecting_journey,question_main_trip_purpose,question_leisure_reason,service_id,trainset,equipment_type,train_service,route_type,origin_theoretical_time,destination_theoretical_time,restriction_open_Toilets,restriction_open_Air Conditioning,restriction_open_Refrigeration,restriction_open_Windows,restriction_open_WiFi,restriction_open_Heating,total restrictions,restriction_days_Toilets,restriction_days_Air Conditioning,restriction_days_Refrigeration,restriction_days_Windows,restriction_days_WiFi,restriction_days_Heating,longest restriction,pm_days_since_catering,pm_days_since_toilet,pm_days_since_climate,pm_days_since_interior,pm_days_since_reliability,pm_days_since_comms,pm_days_since_wifi,average days since last exams,pm_has_prior_catering,pm_has_prior_toilet,pm_has_prior_climate,pm_has_prior_interior,pm_has_prior_reliability,pm_has_prior_comms,pm_has_prior_wifi,cm_open_climate,cm_open_wifi,cm_open_interior,cm_open_catering,cm_open_toilet,cm_open_cleaning,total open faults,clean_score_routine,clean_hours_since_routine,clean_score_deep,clean_days_since_deep,last_clean_score,hours_since_last_clean,clean_has_prior_routine,clean_has_prior_deep,n_trainsets,early_journey_delay_minute,arrival_delay_minute,compensation_liability_evouchers,compensation_liability_cash,delay_cause_id,Departure Date_x,Movement Number_x,Departure Delay (Minutes)_x,Arrival Delay (Minutes),Actor Name_x,Is Station Departure Service,Is Station Arrival Service,Origin Station Name_x,Destination Station Name_x,Cause Category_x,Cause Domain_x,Cause Responsibility_x,Departure Date_y,Movement Number_y,Departure Delay (Minutes)_y,Origin Station Name_y,Destination Station Name_y,Actor Name_y,Cause Category_y,Cause Domain_y,Cause Responsibility_y,Rame Number,Travel Number,Theoretical Rotation Time,Effective Rotation Time,Exceeded Rotation Time,Date,met_departures,ordered_departures,unmet_departures,fleet_reliability,total_met_departures,total_ordered_departures,total_unmet_departures,total_fleet_reliability
0,2024-10-01T14:58:17Z,Eurostar Standard,1.00,12.00,0.00,EUR,2.00,1.00,20250101,18:04,Amsterdam Centraal,5.00,None,London St Pancras Int'l,21.00,144.00,None,None,None,None,8.00,None,209,Blue,1.00,33.00,Small Business,6.00,Classique,3.00,9152.00,E320,2.00,1.00,2025-01-02T15:05:35Z,2025-01-02T15:02:05Z,5,2,4,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,5,<NA>,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,4,<NA>,<NA>,<NA>,4,5,['It was the most environmentally-friendly opt...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,3,Range of food/drink available at the Eurostar ...,<NA>,None,<NA>,None,United Kingdom,Between 26 - 34,4,4,3,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9152_20250101,4009+4010,E320,9152,Channel,2025-01-01 18:04:00+00:00,2025-01-01 23:20:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.00,26.00,26.00,128.00,232.00,2695.00,NaN,529.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,95.83,0.33,NaN,NaN,95.83,0.33,1,0,2,2.00,1.00,0.00,0.00,NaN,2025-01-01,9152,0.00,0.90,PRORAIL,False,True,St-Pancras-International,Amsterdam-Centraal,I6 - Traffic Regulation,Infrastructure Manager,External,2025-01-01,9152,0.00,St-Pancras-International,Amsterdam-Centraal,PRORAIL,I6 - Traffic Regulation,Infrastructure Manager,External,4010-4009,3.00,94.00,96.02,2.02,2025-01-01,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67
1,2024-11-22T06:45:54Z,Eurostar Standard,1.00,2.00,0.00,GBP,2.00,7.00,20250101,12:56,London St Pancras Int'l,21.00,None,Brussels Midi / Zuid,9.00,115.00,None,Wifi was not working,None,None,10.00,None,201,Blue,1.00,65.00,None,NaN,Classique,3.00,9135.00,E300,1.00,1.00,2025-01-02T15:05:37Z,2025-01-02T15:02:15Z,5,1,5,4,4,4,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,3,<NA>,4,4,4,<NA>,<NA>,<NA>,<NA>,5,5,5,<NA>,<NA>,<NA>,5,5,['It was the cheapest option' 'It was the quic...,Eurostar would be my preferred choice,<NA>,<NA>,None,None,<NA>,<NA>,None,<NA>,None,4,At security (baggage checks/scanning),United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a main holiday,9135_20250101,3221+3222,E300,9135,Channel,2025-01-01 12:56:00+00:00,2025-01-01 13:57:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.00,3623.00,212.00,293.00,171.00,1904.00,NaN,1047.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,9.00,7.00,0.00,0.00,14.00,2025-01-01,9135,0.00,60.00,EUROSTAR,False,True,Bruxelles-Midi,St-Pancras-International,S1 - Passengers,Stations,Internal,2025-01-01,9135,7.70,Bruxelles-Midi,St-Pancras-International,EUROSTAR,S1 - Passengers,Stations,Internal,NaN,NaN,NaN,NaN,NaN,2025-01-01,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67
2,2024-12-26T03:54:23Z,Eurostar Standard,1.00,10.00,0.00,EUR,2.00,2.00,20250101,19:34,Brussels Midi / Zuid,9.00,None,London St Pancras Int'l,21.00,134.00,None,The departing gate in London was very crowded ...,None,None,9.00,None,175,Blue,1.00,11.00,Small Business,6.00,Classique,3.00,9158.00,E320,2.00,2.00,2025-01-02T15:07:01Z,2025-01-02T15:04:05Z,5,4,2,5,5,4,4,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,4,<NA>,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,5,['It was the quickest option'\n 'It was the mo...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,<NA>,The availability of toilet facilities on board,<NA>,None,<NA>,None,Belgium,Between 26 - 34,4,4,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9158_20250101,4033+4034,E320,9158,Channel,2025-01-01 19:34:00+00:00,2025-01-01 22:35:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.00,50.00,37.00,5.00,202.00,NaN,NaN,68.60,1,1,1,1,1,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,3.00,2.00,0.00,0.00,NaN,2025-01-01,9158,0.00,2.40,EUROTUNNEL,False,True,St-Pancras-International,Bruxelles-Midi,I4 - Infrastructure Fault,Infrastructure Manager,External,2025-01-01,9158,0.00,St-Pancras-International,Bruxelles-Midi,EUROTUNNEL,I4 - Infrastructure Fault,Infrastructure Manager,External,4033-4034,4.00,97.00,NaN,0.00,2025-01-01,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67
3,2024-12-29T15:45:51Z,Eurostar Premier,3.00,11.00,0.00,EUR,2.00,14.00,20250101,19:10,Paris Gare du Nord,25.00,None,Amsterdam Centraal,5.00,132.00,None,"none, it was all good",None,None,10.00,None,204,Red,2.00,74.00,None,NaN,None,NaN,9388.00,TGH,6.00,1.00,2025-01-02T15:07:04Z,2025-01-02T15:03:39Z,5,<NA>,5,5,5,4,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,4,5,5,5,4,3,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Did you use the Eurostar Lounge at ${e://Field...,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,5,<NA>,5,5,5,5,5,['It was the quickest option'\n 'To avoid addi...,Eurostar would be my preferred choice,5,3,No,None,<NA>,<NA>,None,5,Disembarking the train,<NA>,None,France,Between 18 - 25,<NA>,<NA>,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9388_20250101,4343,TGH,9388,Continental,2025-01-01 19:10:00+00:00,2025-01-01 22:40:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,NaN,89.00,50.50,0,0,0,0,1,0,1,5.00,0.00,6.00,15.00,6.00,2.00,34.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,5.00,14.00,0.00,0.00,14.00,2025-01-01,9388,0.00,12.70,None,False,True,Amsterdam-Centraal,Paris-Nord,Z1 - Weather related - Safety measures / Speed...,Force Majeure (No compensation),External,2025-01-01,9388,5.70,Amsterdam-Centraal,Paris-Nord,EUROSTAR,S1 - Passengers,Stations,Internal,4343,4.00,80.00,47.88,0.00,2025-01-01,11.00,12.00,-1.00,91.67,29.00,30.00,-1.00,96.67
4,2024-07-24T14:45:14Z,Eurostar Standard,1.00,12.00,0.00,GBP,2.00,1.00,20250101,14:42,London St Pancras Int'l,21.00,None,Paris Gare du Nord,25.00,54.00,None,I thought the facilities were great at Paris G...,None,None,8.00,None,309,Blue,1.00,33.00,None,NaN,Classique,3.00,9037.00,E320,2.00,2.00,2025-01-02T15:07:25Z,2025-01-02T15:02:15Z,4,3,5,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,4,4,<NA>,<NA>,<NA>,5,5,['It was the most environmentally-friendly opt...,Eurostar would be my preferred choice,5,<NA>,None,None,<NA>,<NA>,None,3,Signage for onward journey and/or connections ...,<NA>,None,United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a short break,9037_20250101,4021+4022,E320,9037,Channel,2025-01-01 14:42:00+00:00,2025-01-01 16:00:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.00,32.00,6.00,85.00,257.00,2793.00,NaN,538.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,4.00,1.00,0.00,0.00,NaN,2025-01-01,9037,0.00,60.00,EUROSTAR,False,True,Paris-Nord,St-Pancras-International,S1 - Passengers,Stations,Internal,2025-01-01,9037,4.30,Paris-Nord,St-Pancras-International,EUROSTAR,S1 - Passengers,Stations,Internal,4021-4022,2.00,113.00,115.53,2.53,2025-01-01,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67
5,2024-11-11T02:29:38Z,Eurostar Standard,1.00,6.00,0.00,EUR,1.00,33.00,20250101,10:25,Amsterdam Centraal,5.00,4|4,Paris Gare du Nord,25.00,63.00,None,"During and after the delay, I kept getting SMS...","Although there was a delay, which was dissatis...",None,8.00,None,304,Red,2.00,15.00,None,NaN,Classique,3.00,9427.00,TGH,6.00,1.00,2025-01-02T15:07:26Z,2025-01-02T15:02:21Z,5,3,4,3,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,4,<NA>,<NA>,4,4,5,<NA>,1,<NA>,3,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,5,5,5,5,5,5,4,['It was the quickest option'\n 'It was the mo...,Eurostar would be my preferred choice,5,<NA>,None,None,<NA>,<NA>,None,5,Disembarking the train,<NA>,None,The Netherlands,Between 18 - 25,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Regular commute,None,9427_20250101,4301,TGH,9427,Continental,2025-01-01 10:25:00+00:00,2025-01-01 13:50:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00,NaN,65.00,36.00,0,0,0,0,1,0,1,4.00,0.00,4.00,12.00,4.00,1.00,25.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0.00,33.00,0.00,0.00,60.00,2025-01-01,9427,0.00,33.80,None,False,True,Paris-Nord,Amsterdam-Centraal,Z1 - Weather related - Safety measures / Speed...,Force Majeure (No compensation),External,2025-01-01,9427,-0.80,Paris-Nord,Amsterdam-Centraal,None,None,None,None,NaN,NaN,NaN,NaN,NaN,2025-01-01,11.00,12.00,-1.00,91.67,29.00,30.00,-1.00,96.67

In [102]:
df.shape

(178833, 246)

In [103]:
df = df.drop(columns=[
    'Date',
    'Actor Name_y',
    'Origin Station Name_y',
    'Destination Station Name_y',
    'Movement Number_y',
    'Departure Date_y',
    'Origin Station Name_x',
    'Destination Station Name_x',
    'Is Station Arrival Service',
    'Is Station Departure Service',
    'Actor Name_x',
    'Movement Number_x',
    'Departure Date_x',
    'Departure Delay (Minutes)_x'
])
print(f'df shape after dropping columns: {df.shape}')

df shape after dropping columns: (178833, 232)

In [104]:
df.head()

,metadata_booking_date,metadata_class_of_service,metadata_class_of_service_code,metadata_coach_number,metadata_compensation_flag,metadata_currency,metadata_delay_code,metadata_delay_at_arrival,metadata_departure_date,metadata_departure_hour,metadata_destination_station,metadata_destination_station_code,metadata_disrup,metadata_origin_station,metadata_origin_station_code,metadata_price,metadata_on_board_the_train_v,metadata_overall_experience_v,metadata_q14_op,metadata_q17_op,metadata_recommendation_nps_a,metadata_assistance_service_v,metadata_q_total_duration,metadata_route,metadata_route_code,metadata_seat_number,metadata_segment,metadata_segment_code,metadata_tier_level,metadata_tier_level_code,metadata_train_number,metadata_train_type,metadata_train_type_code,metadata_trips_l12_months,metadata_end_date,metadata_start_date,question_overall_satisfaction_booking_experience,question_overall_satisfaction_wifi_onboard_the_train,question_overall_satisfaction_experience_at_departure_station,question_overall_satisfaction_journey_punctuality,question_overall_satisfaction_comfort_onboard_the_train,question_overall_satisfaction_cleanliness_onboard_the_train,question_overall_satisfaction_overall_service_from_eurostar_staff,question_overall_satisfaction_information_provided_to_you_before_travelling,question_lounge_overall_f_b_your_overall_experience_in_the_premier_lounge,question_lounge_overall_f_b_the_beverage_offering_in_the_lounge,question_lounge_overall_f_b_available_space_seating,question_lounge_overall_f_b_lounge_staff,question_lounge_overall_f_b_cocktail_bar,question_lounge_overall_f_b_newspapers_magazines,question_lounge_overall_f_b_your_welcome_arrival_at_the_lounge,question_lounge_overall_f_b_atmosphere_ambience_in_the_lounge,question_lounge_overall_f_b_furniture_and_d_cor_in_the_lounge,question_lounge_overall_f_b_information_regarding_your_train_departure,question_lounge_overall_f_b_cleanliness_of_the_lounge,question_lounge_overall_f_b_the_food_offering_in_the_lounge,question_lounge_improvement,question_onboard_catering_met_quality_of_food_in_meal_service,question_onboard_catering_met_receiving_preferred_meal_option,question_onboard_catering_met_quality_of_beverages_in_meal_service,question_onboard_catering_met_staff_hospitality_during_meal_service,question_onboard_catering_met_portion_sizes,question_onboard_catering_met_range_of_food_available_in_meal_service,question_onboard_catering_met_range_of_drinks_available_in_meal_service,question_onboard_catering_met_presentation_of_food,question_disruption_performan_the_information_available_to_you,question_disruption_performan_the_compensation_you_received_as_a_result_of_this_disruption,question_disruption_performan_frequency_regularity_of_updates,question_disruption_performan_the_accuracy_of_all_information_provided,question_disruption_performan_the_consistency_of_information_from_different_sources,question_disruption_performan_the_frequency_with_which_you_were_kept_updated,question_disruption_performan_information_provided_in_stations_e_g_from_staff_on_screens,question_disruption_performan_information_on_board_the_train_e_g_from_staff_announcements,question_disruption_performan_information_available_through_the_eurostar_website_or_app,question_disruption_performan_information_received_from_eurostar_via_e_mail_or_sms,question_disruption_performan_passenger_care_hotel_taxi_food_boxes,question_disruption_performan_eurostar_s_overall_management_of_this_disruption,question_usage_hv,question_disability_and_acces,question_assistance_service,question_assistance_service_r,question_language,question_at_the_station_checking_in_to_departures_area,question_at_the_station_boarding_the_train,question_at_the_station_toilets_washrooms_in_the_station,question_at_the_station_the_security_process_baggage_checks_and_scanners,question_at_the_station_passport_control,question_at_the_station_pre_departure_announcements_in_the_station,question_at_the_station_available_space_seating_in_the_waiting_area,question_at_the_station_the_facilities_in_the_waiting_area,question_at_the_station_the_signage_and_directions_to_your_platform_and_train,question_on_board_the_train1_the_noise_on_board,question_on_board_the_train1_the_atmosphere_on_board,question_on_board_the_train1_the_temperature_on_board,question_on_board_the_train1_the_level_of_comfort_on_board,question_on_board_the_train1_the_availability_of_toilet_facilities_on_board,question_on_board_the_train1_the_cleanliness_on_board_the_train,question_on_board_the_train1_seat_comfort,question_arrival_the_goodbye_you_received_from_train_staff_when_you_reached_your_destination,question_arrival_disembarking_the_train,question_arrival_signage_for_onward_journey_and_or_connections_at_destination_station,question_arrival_onboard_announcement_on_arrival_by_train_manager,question_staff_on_board_cleaning_staff,question_staff_on_board_train_manager,question_service_provided_by_when_getting_in_touch_via_the_contact_centre,question_service_provided_by_at_the_departure_station,question_service_provided_by_at_the_ticket_gates,question_service_provided_by_at_security_baggage_checks_scanning,question_service_provided_by_on_the_train,question_service_provided_by_train_manager,question_service_provided_by_at_the_eurostar_caf_onboard,question_service_provided_by_at_your_destination_station,question_staff_manners_staff_were_visible,question_staff_manners_staff_were_friendly_and_welcoming,question_staff_manners_staff_were_helpful,question_impact_of_cleaning_p_this_cleaning_process_is_important_to_ensure_your_comfort_on_the_train,question_impact_of_cleaning_p_this_cleaning_process_helps_to_reinforce_your_satisfaction_with_eurostar,question_impact_of_cleaning_p_this_cleaning_process_encourages_you_to_choose_eurostar_again_in_the_future,question_ticket_price_satisfa,question_overall_rating,question_reasons_for_choosing,question_future_consideration,question_strategic_pillar_ass_travelling_by_eurostar_is_an_environmentally_sustainable_option,question_strategic_pillar_ass_eurostar_manages_its_food_and_drink_offering_at_station_lounges_and_onboard_in_an_environmentally_sustainable_way,question_lounge_usage,question_hv_11,question_hv_12,question_hv_22,question_hv_21,question_hv_32,question_hv_31,question_hv_42,question_hv_41,question_residence,question_age,question_on_board_the_train2_the_cleanliness_of_toilet_facilities_on_board_the_train,question_on_board_the_train2_the_information_and_announcements_provided_on_board,question_on_board_the_train2_range_of_food_drink_available_at_the_eurostar_caf,question_on_board_the_train2_the_wi_fi_on_board,question_qid61_nps_group,question_onboard_catering_ove,question_visit_cafe,question_eurostar_cafe_your_overall_experience_at_the_eurostar_caf,question_eurostar_cafe_the_service_you_received_from_staff,question_eurostar_cafe_the_quality_of_the_food,question_eurostar_cafe_the_quality_of_the_drinks,question_eurostar_cafe_the_range_of_food_on_offer,question_eurostar_cafe_the_range_of_drinks_on_offer,question_eurostar_cafe_the_prices_value_for_money_of_food_and_drinks,question_eurostar_cafe_the_product_availabilty,question_purchase_cafe,question_connecting_journey,question_main_trip_purpose,question_leisure_reason,service_id,trainset,equipment_type,train_service,route_type,origin_theoretical_time,destination_theoretical_time,restriction_open_Toilets,restriction_open_Air Conditioning,restriction_open_Refrigeration,restriction_open_Windows,restriction_open_WiFi,restriction_open_Heating,total restrictions,restriction_days_Toilets,restriction_days_Air Conditioning,restriction_days_Refrigeration,restriction_days_Windows,restriction_days_WiFi,restriction_days_Heating,longest restriction,pm_days_since_catering,pm_days_since_toilet,pm_days_since_climate,pm_days_since_interior,pm_days_since_reliability,pm_days_since_comms,pm_days_since_wifi,average days since last exams,pm_has_prior_catering,pm_has_prior_toilet,pm_has_prior_climate,pm_has_prior_interior,pm_has_prior_reliability,pm_has_prior_comms,pm_has_prior_wifi,cm_open_climate,cm_open_wifi,cm_open_interior,cm_open_catering,cm_open_toilet,cm_open_cleaning,total open faults,clean_score_routine,clean_hours_since_routine,clean_score_deep,clean_days_since_deep,last_clean_score,hours_since_last_clean,clean_has_prior_routine,clean_has_prior_deep,n_trainsets,early_journey_delay_minute,arrival_delay_minute,compensation_liability_evouchers,compensation_liability_cash,delay_cause_id,Arrival Delay (Minutes),Cause Category_x,Cause Domain_x,Cause Responsibility_x,Departure Delay (Minutes)_y,Cause Category_y,Cause Domain_y,Cause Responsibility_y,Rame Number,Travel Number,Theoretical Rotation Time,Effective Rotation Time,Exceeded Rotation Time,met_departures,ordered_departures,unmet_departures,fleet_reliability,total_met_departures,total_ordered_departures,total_unmet_departures,total_fleet_reliability
0,2024-10-01T14:58:17Z,Eurostar Standard,1.00,12.00,0.00,EUR,2.00,1.00,20250101,18:04,Amsterdam Centraal,5.00,None,London St Pancras Int'l,21.00,144.00,None,None,None,None,8.00,None,209,Blue,1.00,33.00,Small Business,6.00,Classique,3.00,9152.00,E320,2.00,1.00,2025-01-02T15:05:35Z,2025-01-02T15:02:05Z,5,2,4,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,5,<NA>,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,4,<NA>,<NA>,<NA>,4,5,['It was the most environmentally-friendly opt...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,3,Range of food/drink available at the Eurostar ...,<NA>,None,<NA>,None,United Kingdom,Between 26 - 34,4,4,3,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9152_20250101,4009+4010,E320,9152,Channel,2025-01-01 18:04:00+00:00,2025-01-01 23:20:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.00,26.00,26.00,128.00,232.00,2695.00,NaN,529.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,95.83,0.33,NaN,NaN,95.83,0.33,1,0,2,2.00,1.00,0.00,0.00,NaN,0.90,I6 - Traffic Regulation,Infrastructure Manager,External,0.00,I6 - Traffic Regulation,Infrastructure Manager,External,4010-4009,3.00,94.00,96.02,2.02,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67
1,2024-11-22T06:45:54Z,Eurostar Standard,1.00,2.00,0.00,GBP,2.00,7.00,20250101,12:56,London St Pancras Int'l,21.00,None,Brussels Midi / Zuid,9.00,115.00,None,Wifi was not working,None,None,10.00,None,201,Blue,1.00,65.00,None,NaN,Classique,3.00,9135.00,E300,1.00,1.00,2025-01-02T15:05:37Z,2025-01-02T15:02:15Z,5,1,5,4,4,4,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,3,<NA>,4,4,4,<NA>,<NA>,<NA>,<NA>,5,5,5,<NA>,<NA>,<NA>,5,5,['It was the cheapest option' 'It was the quic...,Eurostar would be my preferred choice,<NA>,<NA>,None,None,<NA>,<NA>,None,<NA>,None,4,At security (baggage checks/scanning),United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a main holiday,9135_20250101,3221+3222,E300,9135,Channel,2025-01-01 12:56:00+00:00,2025-01-01 13:57:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.00,3623.00,212.00,293.00,171.00,1904.00,NaN,1047.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,9.00,7.00,0.00,0.00,14.00,60.00,S1 - Passengers,Stations,Internal,7.70,S1 - Passengers,Stations,Internal,NaN,NaN,NaN,NaN,NaN,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67
2,2024-12-26T03:54:23Z,Eurostar Standard,1.00,10.00,0.00,EUR,2.00,2.00,20250101,19:34,Brussels Midi / Zuid,9.00,None,London St Pancras Int'l,21.00,134.00,None,The departing gate in London was very crowded ...,None,None,9.00,None,175,Blue,1.00,11.00,Small Business,6.00,Classique,3.00,9158.00,E320,2.00,2.00,2025-01-02T15:07:01Z,2025-01-02T15:04:05Z,5,4,2,5,5,4,4,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,4,<NA>,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,5,['It was the quickest option'\n 'It was the mo...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,<NA>,The availability of toilet facilities on board,<NA>,None,<NA>,None,Belgium,Between 26 - 34,4,4,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9158_20250101,4033+4034,E320,9158,Channel,2025-01-01 19:34:00+00:00,2025-01-01 22:35:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.00,50.00,37.00,5.00,202.00,NaN,NaN,68.60,1,1,1,1,1,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,3.00,2.00,0.00,0.00,NaN,2.40,I4 - Infrastructure Fault,Infrastructure Manager,External,0.00,I4 - Infrastructure Fault,Infrastructure Manager,External,4033-4034,4.00,97.00,NaN,0.00,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67
3,2024-12-29T15:45:51Z,Eurostar Premier,3.00,11.00,0.00,EUR,2.00,14.00,20250101,19:10,Paris Gare du Nord,25.00,None,Amsterdam Centraal,5.00,132.00,None,"none, it was all good",None,None,10.00,None,204,Red,2.00,74.00,None,NaN,None,NaN,9388.00,TGH,6.00,1.00,2025-01-02T15:07:04Z,2025-01-02T15:03:39Z,5,<NA>,5,5,5,4,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,4,5,5,5,4,3,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Did you use the Eurostar Lounge at ${e://Field...,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,5,<NA>,5,5,5,5,5,['It was the quickest option'\n 'To avoid addi...,Eurostar would be my preferred choice,5,3,No,None,<NA>,<NA>,None,5,Disembarking the train,<NA>,None,France,Between 18 - 25,<NA>,<NA>,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9388_20250101,4343,TGH,9388,Continental,2025-01-01 19:10:00+00:00,2025-01-01 22:40:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,NaN,89.00,50.50,0,0,0,0,1,0,1,5.00,0.00,6.00,15.00,6.00,2.00,34.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,5.00,14.00,0.00,0.00,14.00,12.70,Z1 - Weather related - Safety measures / Speed...,Force Majeure (No compensation),External,5.70,S1 - Passengers,Stations,Internal,4343,4.00,80.00,47.88,0.00,11.00,12.00,-1.00,91.67,29.00,30.00,-1.00,96.67
4,2024-07-24T14:45:14Z,Eurostar Standard,1.00,12.00,0.00,GBP,2.00,1.00,20250101,14:42,London St Pancras Int'l,21.00,None,Paris Gare du Nord,25.00,54.00,None,I thought the facilities were great at Paris G...,None,None,8.00,None,309,Blue,1.00,33.00,None,NaN,Classique,3.00,9037.00,E320,2.00,2.00,2025-01-02T15:07:25Z,2025-01-02T15:02:15Z,4,3,5,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,4,4,<NA>,<NA>,<NA>,5,5,['It was the most environmentally-friendly opt...,Eurostar would be my preferred choice,5,<NA>,None,None,<NA>,<NA>,None,3,Signage for onward journey and/or connections ...,<NA>,None,United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a short break,9037_20250101,4021+4022,E320,9037,Channel,2025-01-01 14:42:00+00:00,2025-01-01 16:00:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.00,32.00,6.00,85.00,257.00,2793.00,NaN,538.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,4.00,1.00,0.00,0.00,NaN,60.00,S1 - Passengers,Stations,Internal,4.30,S1 - Passengers,Stations,Internal,4021-4022,2.00,113.00,115.53,2.53,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67

In [105]:
df = df.rename(columns={
    'Arrival Delay (Minutes)': 'Arrival Delay',
    'Departure Delay (Minutes)_y': 'Departure Delay',
    'metadata_recommendation_nps_a': 'metadata_nps'
})

In [106]:
counts = df.groupby('service_id').size()
print(f'service_ids with 1 row:  {(counts == 1).sum()}')
print(f'service_ids with >1 row: {(counts > 1).sum()}')
print(f'\nFull distribution:')
print(counts.value_counts().sort_index())

service_ids with 1 row:  9353
service_ids with >1 row: 36511

Full distribution:
1     9353
2     8910
3     7343
4     5641
5     4161
6     3103
7     2227
8     1518
9     1126
10     832
11     531
12     373
13     265
14     141
15     111
16      92
17      49
18      34
19      18
20      12
21       9
22       7
23       3
24       3
33       1
40       1
Name: count, dtype: int64

In [107]:
df = df[df.groupby('service_id')['service_id'].transform('count') > 1]
print(f'df shape after removing service_ids with only 1 row: {df.shape}')

df shape after removing service_ids with only 1 row: (169480, 232)

In [108]:
df['Aggregated Delay'] = df['Departure Delay'] + df['Arrival Delay']

In [109]:
def nps_category(score):
    if score >= 9:
        return 'promoter'
    elif score >= 7:
        return 'neutral'
    else:
        return 'detractor'

df['nps_category'] = df['metadata_nps'].apply(nps_category)

df['Aggregated NPS'] = df.groupby('service_id')['nps_category'].transform(
    lambda x: round((x == 'promoter').sum() / len(x) * 100 - (x == 'detractor').sum() / len(x) * 100, 2))

In [110]:
df.head(10)

,metadata_booking_date,metadata_class_of_service,metadata_class_of_service_code,metadata_coach_number,metadata_compensation_flag,metadata_currency,metadata_delay_code,metadata_delay_at_arrival,metadata_departure_date,metadata_departure_hour,metadata_destination_station,metadata_destination_station_code,metadata_disrup,metadata_origin_station,metadata_origin_station_code,metadata_price,metadata_on_board_the_train_v,metadata_overall_experience_v,metadata_q14_op,metadata_q17_op,metadata_nps,metadata_assistance_service_v,metadata_q_total_duration,metadata_route,metadata_route_code,metadata_seat_number,metadata_segment,metadata_segment_code,metadata_tier_level,metadata_tier_level_code,metadata_train_number,metadata_train_type,metadata_train_type_code,metadata_trips_l12_months,metadata_end_date,metadata_start_date,question_overall_satisfaction_booking_experience,question_overall_satisfaction_wifi_onboard_the_train,question_overall_satisfaction_experience_at_departure_station,question_overall_satisfaction_journey_punctuality,question_overall_satisfaction_comfort_onboard_the_train,question_overall_satisfaction_cleanliness_onboard_the_train,question_overall_satisfaction_overall_service_from_eurostar_staff,question_overall_satisfaction_information_provided_to_you_before_travelling,question_lounge_overall_f_b_your_overall_experience_in_the_premier_lounge,question_lounge_overall_f_b_the_beverage_offering_in_the_lounge,question_lounge_overall_f_b_available_space_seating,question_lounge_overall_f_b_lounge_staff,question_lounge_overall_f_b_cocktail_bar,question_lounge_overall_f_b_newspapers_magazines,question_lounge_overall_f_b_your_welcome_arrival_at_the_lounge,question_lounge_overall_f_b_atmosphere_ambience_in_the_lounge,question_lounge_overall_f_b_furniture_and_d_cor_in_the_lounge,question_lounge_overall_f_b_information_regarding_your_train_departure,question_lounge_overall_f_b_cleanliness_of_the_lounge,question_lounge_overall_f_b_the_food_offering_in_the_lounge,question_lounge_improvement,question_onboard_catering_met_quality_of_food_in_meal_service,question_onboard_catering_met_receiving_preferred_meal_option,question_onboard_catering_met_quality_of_beverages_in_meal_service,question_onboard_catering_met_staff_hospitality_during_meal_service,question_onboard_catering_met_portion_sizes,question_onboard_catering_met_range_of_food_available_in_meal_service,question_onboard_catering_met_range_of_drinks_available_in_meal_service,question_onboard_catering_met_presentation_of_food,question_disruption_performan_the_information_available_to_you,question_disruption_performan_the_compensation_you_received_as_a_result_of_this_disruption,question_disruption_performan_frequency_regularity_of_updates,question_disruption_performan_the_accuracy_of_all_information_provided,question_disruption_performan_the_consistency_of_information_from_different_sources,question_disruption_performan_the_frequency_with_which_you_were_kept_updated,question_disruption_performan_information_provided_in_stations_e_g_from_staff_on_screens,question_disruption_performan_information_on_board_the_train_e_g_from_staff_announcements,question_disruption_performan_information_available_through_the_eurostar_website_or_app,question_disruption_performan_information_received_from_eurostar_via_e_mail_or_sms,question_disruption_performan_passenger_care_hotel_taxi_food_boxes,question_disruption_performan_eurostar_s_overall_management_of_this_disruption,question_usage_hv,question_disability_and_acces,question_assistance_service,question_assistance_service_r,question_language,question_at_the_station_checking_in_to_departures_area,question_at_the_station_boarding_the_train,question_at_the_station_toilets_washrooms_in_the_station,question_at_the_station_the_security_process_baggage_checks_and_scanners,question_at_the_station_passport_control,question_at_the_station_pre_departure_announcements_in_the_station,question_at_the_station_available_space_seating_in_the_waiting_area,question_at_the_station_the_facilities_in_the_waiting_area,question_at_the_station_the_signage_and_directions_to_your_platform_and_train,question_on_board_the_train1_the_noise_on_board,question_on_board_the_train1_the_atmosphere_on_board,question_on_board_the_train1_the_temperature_on_board,question_on_board_the_train1_the_level_of_comfort_on_board,question_on_board_the_train1_the_availability_of_toilet_facilities_on_board,question_on_board_the_train1_the_cleanliness_on_board_the_train,question_on_board_the_train1_seat_comfort,question_arrival_the_goodbye_you_received_from_train_staff_when_you_reached_your_destination,question_arrival_disembarking_the_train,question_arrival_signage_for_onward_journey_and_or_connections_at_destination_station,question_arrival_onboard_announcement_on_arrival_by_train_manager,question_staff_on_board_cleaning_staff,question_staff_on_board_train_manager,question_service_provided_by_when_getting_in_touch_via_the_contact_centre,question_service_provided_by_at_the_departure_station,question_service_provided_by_at_the_ticket_gates,question_service_provided_by_at_security_baggage_checks_scanning,question_service_provided_by_on_the_train,question_service_provided_by_train_manager,question_service_provided_by_at_the_eurostar_caf_onboard,question_service_provided_by_at_your_destination_station,question_staff_manners_staff_were_visible,question_staff_manners_staff_were_friendly_and_welcoming,question_staff_manners_staff_were_helpful,question_impact_of_cleaning_p_this_cleaning_process_is_important_to_ensure_your_comfort_on_the_train,question_impact_of_cleaning_p_this_cleaning_process_helps_to_reinforce_your_satisfaction_with_eurostar,question_impact_of_cleaning_p_this_cleaning_process_encourages_you_to_choose_eurostar_again_in_the_future,question_ticket_price_satisfa,question_overall_rating,question_reasons_for_choosing,question_future_consideration,question_strategic_pillar_ass_travelling_by_eurostar_is_an_environmentally_sustainable_option,question_strategic_pillar_ass_eurostar_manages_its_food_and_drink_offering_at_station_lounges_and_onboard_in_an_environmentally_sustainable_way,question_lounge_usage,question_hv_11,question_hv_12,question_hv_22,question_hv_21,question_hv_32,question_hv_31,question_hv_42,question_hv_41,question_residence,question_age,question_on_board_the_train2_the_cleanliness_of_toilet_facilities_on_board_the_train,question_on_board_the_train2_the_information_and_announcements_provided_on_board,question_on_board_the_train2_range_of_food_drink_available_at_the_eurostar_caf,question_on_board_the_train2_the_wi_fi_on_board,question_qid61_nps_group,question_onboard_catering_ove,question_visit_cafe,question_eurostar_cafe_your_overall_experience_at_the_eurostar_caf,question_eurostar_cafe_the_service_you_received_from_staff,question_eurostar_cafe_the_quality_of_the_food,question_eurostar_cafe_the_quality_of_the_drinks,question_eurostar_cafe_the_range_of_food_on_offer,question_eurostar_cafe_the_range_of_drinks_on_offer,question_eurostar_cafe_the_prices_value_for_money_of_food_and_drinks,question_eurostar_cafe_the_product_availabilty,question_purchase_cafe,question_connecting_journey,question_main_trip_purpose,question_leisure_reason,service_id,trainset,equipment_type,train_service,route_type,origin_theoretical_time,destination_theoretical_time,restriction_open_Toilets,restriction_open_Air Conditioning,restriction_open_Refrigeration,restriction_open_Windows,restriction_open_WiFi,restriction_open_Heating,total restrictions,restriction_days_Toilets,restriction_days_Air Conditioning,restriction_days_Refrigeration,restriction_days_Windows,restriction_days_WiFi,restriction_days_Heating,longest restriction,pm_days_since_catering,pm_days_since_toilet,pm_days_since_climate,pm_days_since_interior,pm_days_since_reliability,pm_days_since_comms,pm_days_since_wifi,average days since last exams,pm_has_prior_catering,pm_has_prior_toilet,pm_has_prior_climate,pm_has_prior_interior,pm_has_prior_reliability,pm_has_prior_comms,pm_has_prior_wifi,cm_open_climate,cm_open_wifi,cm_open_interior,cm_open_catering,cm_open_toilet,cm_open_cleaning,total open faults,clean_score_routine,clean_hours_since_routine,clean_score_deep,clean_days_since_deep,last_clean_score,hours_since_last_clean,clean_has_prior_routine,clean_has_prior_deep,n_trainsets,early_journey_delay_minute,arrival_delay_minute,compensation_liability_evouchers,compensation_liability_cash,delay_cause_id,Arrival Delay,Cause Category_x,Cause Domain_x,Cause Responsibility_x,Departure Delay,Cause Category_y,Cause Domain_y,Cause Responsibility_y,Rame Number,Travel Number,Theoretical Rotation Time,Effective Rotation Time,Exceeded Rotation Time,met_departures,ordered_departures,unmet_departures,fleet_reliability,total_met_departures,total_ordered_departures,total_unmet_departures,total_fleet_reliability,Aggregated Delay,nps_category,Aggregated NPS
0,2024-10-01T14:58:17Z,Eurostar Standard,1.00,12.00,0.00,EUR,2.00,1.00,20250101,18:04,Amsterdam Centraal,5.00,None,London St Pancras Int'l,21.00,144.00,None,None,None,None,8.00,None,209,Blue,1.00,33.00,Small Business,6.00,Classique,3.00,9152.00,E320,2.00,1.00,2025-01-02T15:05:35Z,2025-01-02T15:02:05Z,5,2,4,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,5,<NA>,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,4,<NA>,<NA>,<NA>,4,5,['It was the most environmentally-friendly opt...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,3,Range of food/drink available at the Eurostar ...,<NA>,None,<NA>,None,United Kingdom,Between 26 - 34,4,4,3,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9152_20250101,4009+4010,E320,9152,Channel,2025-01-01 18:04:00+00:00,2025-01-01 23:20:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.00,26.00,26.00,128.00,232.00,2695.00,NaN,529.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,95.83,0.33,NaN,NaN,95.83,0.33,1,0,2,2.00,1.00,0.00,0.00,NaN,0.90,I6 - Traffic Regulation,Infrastructure Manager,External,0.00,I6 - Traffic Regulation,Infrastructure Manager,External,4010-4009,3.00,94.00,96.02,2.02,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67,0.90,neutral,0.00
1,2024-11-22T06:45:54Z,Eurostar Standard,1.00,2.00,0.00,GBP,2.00,7.00,20250101,12:56,London St Pancras Int'l,21.00,None,Brussels Midi / Zuid,9.00,115.00,None,Wifi was not working,None,None,10.00,None,201,Blue,1.00,65.00,None,NaN,Classique,3.00,9135.00,E300,1.00,1.00,2025-01-02T15:05:37Z,2025-01-02T15:02:15Z,5,1,5,4,4,4,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,3,<NA>,4,4,4,<NA>,<NA>,<NA>,<NA>,5,5,5,<NA>,<NA>,<NA>,5,5,['It was the cheapest option' 'It was the quic...,Eurostar would be my preferred choice,<NA>,<NA>,None,None,<NA>,<NA>,None,<NA>,None,4,At security (baggage checks/scanning),United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a main holiday,9135_20250101,3221+3222,E300,9135,Channel,2025-01-01 12:56:00+00:00,2025-01-01 13:57:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.00,3623.00,212.00,293.00,171.00,1904.00,NaN,1047.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,9.00,7.00,0.00,0.00,14.00,60.00,S1 - Passengers,Stations,Internal,7.70,S1 - Passengers,Stations,Internal,NaN,NaN,NaN,NaN,NaN,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67,67.70,promoter,50.00
2,2024-12-26T03:54:23Z,Eurostar Standard,1.00,10.00,0.00,EUR,2.00,2.00,20250101,19:34,Brussels Midi / Zuid,9.00,None,London St Pancras Int'l,21.00,134.00,None,The departing gate in London was very crowded ...,None,None,9.00,None,175,Blue,1.00,11.00,Small Business,6.00,Classique,3.00,9158.00,E320,2.00,2.00,2025-01-02T15:07:01Z,2025-01-02T15:04:05Z,5,4,2,5,5,4,4,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,4,<NA>,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,5,['It was the quickest option'\n 'It was the mo...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,<NA>,The availability of toilet facilities on board,<NA>,None,<NA>,None,Belgium,Between 26 - 34,4,4,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9158_20250101,4033+4034,E320,9158,Channel,2025-01-01 19:34:00+00:00,2025-01-01 22:35:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.00,50.00,37.00,5.00,202.00,NaN,NaN,68.60,1,1,1,1,1,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,3.00,2.00,0.00,0.00,NaN,2.40,I4 - Infrastructure Fault,Infrastructure Manager,External,0.00,I4 - Infrastructure Fault,Infrastructure Manager,External,4033-4034,4.00,97.00,NaN,0.00,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67,2.40,promoter,50.00
4,2024-07-24T14:45:14Z,Eurostar Standard,1.00,12.00,0.00,GBP,2.00,1.00,20250101,14:42,London St Pancras Int'l,21.00,None,Paris Gare du Nord,25.00,54.00,None,I thought the facilities were great at Paris G...,None,None,8.00,None,309,Blue,1.00,33.00,None,NaN,Classique,3.00,9037.00,E320,2.00,2.00,2025-01-02T15:07:25Z,2025-01-02T15:02:15Z,4,3,5,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,4,4,<NA>,<NA>,<NA>,5,5,['It was the most environmentally-friendly opt...,Eurostar would be my preferred choice,5,<NA>,None,None,<NA>,<NA>,None,3,Signage for onward journey and/or connections ...,<NA>,None,United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a short break,9037_20250101,4021+4022,E320,9037,Channel,2025-01-01 14:42:00+00:00,2025-01-01 16:00:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.00,32.00,6.00,85.00,257.00,2793.00,NaN,538.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,4.00,1.00,0.00,0.00,NaN,60.00,S1 - Passengers,Stations,Internal,4.30,S1 - Passengers,Stations,Internal,4021-4022,2.00,113.00,115.53,2.53,18.00,18.00,0.00,100.00,29.00,30.00,-1.00,96.67,64.30,neutral,50.00
5,2024-11-11T02:29:38Z,Eurostar Standard,1.00,6.00,0.00,EUR,1.00,33.00,20250101,10:25,Amsterdam Centraal,5.00,4|4,Paris Gare du Nord,25.00,63.00,None,"During and after the delay, I kept getting SMS...","Although there was a delay, which was dissatis...",None,8.00,None,304,Red,2.00,15.00,None,NaN,Classique,3.00,9427.00,TGH,6.00,1.00,2025-01-02T15:07:26Z,2025-01-02T15:02:21Z,5,3,4,3,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,4,<NA>,<NA>,4,4,5,<NA>,1,<NA>,3,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,5,5,5,5,5,5,4,['It was the quickest option'\n 'It was the mo...,Eurostar would be my preferred choice,5,<NA>,None,None,<NA>,<NA>,None,5,Disembarking the train,<NA>,None,The Netherlands,Between 18 - 25,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Regular commute,None,9427_20250101,4301,TGH,9427,Continental,2025-01-01 10:25:00+00:00,2025-01-01 13:50:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00,NaN,65.00,36.00,0,0,0,0,1,0,1,4.00,0.00,4.00,12.00,4.00,1.00,25.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0.00,33.00,0.00,0.00,60.00,33.80,Z1 - Weather related - Safety measures / Speed...,Force Majeure (No compensation),External,-0.80,None,None,None,NaN,NaN,NaN,NaN,NaN,11.00,12.00,-1.00,91.67,29.00,30.00,-1.00,96.67,33.00,neutral,20.00
6,2024-12-07T09:25:15Z,Eurostar Standard,1.00,6.00,0.00,EUR,2.00,0.00,20250101,10:25,Brussels Midi / Zuid,9.00,None,Paris Gare du Nord,25.00,95.00,None,None,None,None,8.00,None,182,Red,2.00,85.00,None,NaN,None,NaN,9427.00,TGH,6.00,1.00,2025-01-02T15:07:26Z,2025-01-02T15:04:23Z,5,1,4,5,4,4,4,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,Dutch,4,4,<NA>,<NA>,<NA>,4,<NA>,<NA>,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,5,4,<NA>,<NA>,<NA>,3,4,['It was the quickest option'],I would consider Eurostar along with other com...,4,<NA>,None,Pre-departure announcements in the station,4,<NA>,None,<NA>,None,<NA>,None,Belgium,Between 18 - 25,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a short break,9427_20250101,4301,TGH,9427,Continental,2025-01-01 10:25:00+00:00,2025-01-01 13:50:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00,NaN,65.00,36.00,0,0,0,0,1,0,1,4.00,0.00,4.00,12.00,4.00,1.00,25.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0.00,33.00,0.00,0.00,60.00,33.80,Z1 - Weather related - Safety measures / Speed...,Force Majeure (No compensation),External,-0.80,None,None,None,NaN,NaN,NaN,NaN,NaN,11.00,12.00,-1.00,91.67,29.00,30.00,-1.00,96.67,33.00,neutral,20.00
7,2025-01-01T11:50:00Z,Eurostar Standard,1.00,5.00,0.00,EUR,1.00,29.00,20250101,19:25,Brussels Midi / Zuid,9.00,2|2,Paris Gare du Nord,25.00,109.00,None,Il faut que vous repreniez en main votre entre...,Vous faites payer ces billets des fortunes et ...,None,0.00,None,310,Red,2.00,44.00,Young VFR,8.00,Avantage,1.00,9481.00,TGH,6.00,9.00,2025-01-02T15:07:31Z,2025-01-02T15:02:21Z,4,3,2,1,3,3,3,2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1,<NA>,2,<NA>,<NA>,2,1,1,2,2,<NA>,2,None,No,None,<NA>,French,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3,3,3,3,3,3,3,3,3,3,3,3,3,<NA>,<NA>,<NA>,1,1,"[""Not my choice/Didn't have any other options""]",I would not consider Eurostar,3,2,None,None,<NA>,<NA>,None,<NA>,None,3,Train manager,Belgium,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Detractor,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a main holiday,9481_20250101,4538,TGH,9481,Continental,2025-01-01 19:25:00+00:00,2025-01-01 20:47:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.00,NaN,127.00,77.00,0,0,0,0,1,0,1,4.00,0.00,22.00,9.00,11.00,4.00,50.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,24.00,29.00,0.00,0.00,35.00,0.00,I6 - Traffic Regulation,Infrastructure Manager,External,0.00,I6 - Traffic Regulation,Infrastructure Manager,External,4538,4.00,47.00,54.88,7.87,11.00,12.00,-1.00,91.67,29.00,30.00,-1.00,96.67,0.00,detractor,-100.00

In [111]:
df['Aggregated NPS'] = df['Aggregated NPS'] / 100
df['fleet_reliability'] = df['fleet_reliability'] / 100
df['total_fleet_reliability'] = df['total_fleet_reliability'] / 100

In [112]:
df.head(10)

,metadata_booking_date,metadata_class_of_service,metadata_class_of_service_code,metadata_coach_number,metadata_compensation_flag,metadata_currency,metadata_delay_code,metadata_delay_at_arrival,metadata_departure_date,metadata_departure_hour,metadata_destination_station,metadata_destination_station_code,metadata_disrup,metadata_origin_station,metadata_origin_station_code,metadata_price,metadata_on_board_the_train_v,metadata_overall_experience_v,metadata_q14_op,metadata_q17_op,metadata_nps,metadata_assistance_service_v,metadata_q_total_duration,metadata_route,metadata_route_code,metadata_seat_number,metadata_segment,metadata_segment_code,metadata_tier_level,metadata_tier_level_code,metadata_train_number,metadata_train_type,metadata_train_type_code,metadata_trips_l12_months,metadata_end_date,metadata_start_date,question_overall_satisfaction_booking_experience,question_overall_satisfaction_wifi_onboard_the_train,question_overall_satisfaction_experience_at_departure_station,question_overall_satisfaction_journey_punctuality,question_overall_satisfaction_comfort_onboard_the_train,question_overall_satisfaction_cleanliness_onboard_the_train,question_overall_satisfaction_overall_service_from_eurostar_staff,question_overall_satisfaction_information_provided_to_you_before_travelling,question_lounge_overall_f_b_your_overall_experience_in_the_premier_lounge,question_lounge_overall_f_b_the_beverage_offering_in_the_lounge,question_lounge_overall_f_b_available_space_seating,question_lounge_overall_f_b_lounge_staff,question_lounge_overall_f_b_cocktail_bar,question_lounge_overall_f_b_newspapers_magazines,question_lounge_overall_f_b_your_welcome_arrival_at_the_lounge,question_lounge_overall_f_b_atmosphere_ambience_in_the_lounge,question_lounge_overall_f_b_furniture_and_d_cor_in_the_lounge,question_lounge_overall_f_b_information_regarding_your_train_departure,question_lounge_overall_f_b_cleanliness_of_the_lounge,question_lounge_overall_f_b_the_food_offering_in_the_lounge,question_lounge_improvement,question_onboard_catering_met_quality_of_food_in_meal_service,question_onboard_catering_met_receiving_preferred_meal_option,question_onboard_catering_met_quality_of_beverages_in_meal_service,question_onboard_catering_met_staff_hospitality_during_meal_service,question_onboard_catering_met_portion_sizes,question_onboard_catering_met_range_of_food_available_in_meal_service,question_onboard_catering_met_range_of_drinks_available_in_meal_service,question_onboard_catering_met_presentation_of_food,question_disruption_performan_the_information_available_to_you,question_disruption_performan_the_compensation_you_received_as_a_result_of_this_disruption,question_disruption_performan_frequency_regularity_of_updates,question_disruption_performan_the_accuracy_of_all_information_provided,question_disruption_performan_the_consistency_of_information_from_different_sources,question_disruption_performan_the_frequency_with_which_you_were_kept_updated,question_disruption_performan_information_provided_in_stations_e_g_from_staff_on_screens,question_disruption_performan_information_on_board_the_train_e_g_from_staff_announcements,question_disruption_performan_information_available_through_the_eurostar_website_or_app,question_disruption_performan_information_received_from_eurostar_via_e_mail_or_sms,question_disruption_performan_passenger_care_hotel_taxi_food_boxes,question_disruption_performan_eurostar_s_overall_management_of_this_disruption,question_usage_hv,question_disability_and_acces,question_assistance_service,question_assistance_service_r,question_language,question_at_the_station_checking_in_to_departures_area,question_at_the_station_boarding_the_train,question_at_the_station_toilets_washrooms_in_the_station,question_at_the_station_the_security_process_baggage_checks_and_scanners,question_at_the_station_passport_control,question_at_the_station_pre_departure_announcements_in_the_station,question_at_the_station_available_space_seating_in_the_waiting_area,question_at_the_station_the_facilities_in_the_waiting_area,question_at_the_station_the_signage_and_directions_to_your_platform_and_train,question_on_board_the_train1_the_noise_on_board,question_on_board_the_train1_the_atmosphere_on_board,question_on_board_the_train1_the_temperature_on_board,question_on_board_the_train1_the_level_of_comfort_on_board,question_on_board_the_train1_the_availability_of_toilet_facilities_on_board,question_on_board_the_train1_the_cleanliness_on_board_the_train,question_on_board_the_train1_seat_comfort,question_arrival_the_goodbye_you_received_from_train_staff_when_you_reached_your_destination,question_arrival_disembarking_the_train,question_arrival_signage_for_onward_journey_and_or_connections_at_destination_station,question_arrival_onboard_announcement_on_arrival_by_train_manager,question_staff_on_board_cleaning_staff,question_staff_on_board_train_manager,question_service_provided_by_when_getting_in_touch_via_the_contact_centre,question_service_provided_by_at_the_departure_station,question_service_provided_by_at_the_ticket_gates,question_service_provided_by_at_security_baggage_checks_scanning,question_service_provided_by_on_the_train,question_service_provided_by_train_manager,question_service_provided_by_at_the_eurostar_caf_onboard,question_service_provided_by_at_your_destination_station,question_staff_manners_staff_were_visible,question_staff_manners_staff_were_friendly_and_welcoming,question_staff_manners_staff_were_helpful,question_impact_of_cleaning_p_this_cleaning_process_is_important_to_ensure_your_comfort_on_the_train,question_impact_of_cleaning_p_this_cleaning_process_helps_to_reinforce_your_satisfaction_with_eurostar,question_impact_of_cleaning_p_this_cleaning_process_encourages_you_to_choose_eurostar_again_in_the_future,question_ticket_price_satisfa,question_overall_rating,question_reasons_for_choosing,question_future_consideration,question_strategic_pillar_ass_travelling_by_eurostar_is_an_environmentally_sustainable_option,question_strategic_pillar_ass_eurostar_manages_its_food_and_drink_offering_at_station_lounges_and_onboard_in_an_environmentally_sustainable_way,question_lounge_usage,question_hv_11,question_hv_12,question_hv_22,question_hv_21,question_hv_32,question_hv_31,question_hv_42,question_hv_41,question_residence,question_age,question_on_board_the_train2_the_cleanliness_of_toilet_facilities_on_board_the_train,question_on_board_the_train2_the_information_and_announcements_provided_on_board,question_on_board_the_train2_range_of_food_drink_available_at_the_eurostar_caf,question_on_board_the_train2_the_wi_fi_on_board,question_qid61_nps_group,question_onboard_catering_ove,question_visit_cafe,question_eurostar_cafe_your_overall_experience_at_the_eurostar_caf,question_eurostar_cafe_the_service_you_received_from_staff,question_eurostar_cafe_the_quality_of_the_food,question_eurostar_cafe_the_quality_of_the_drinks,question_eurostar_cafe_the_range_of_food_on_offer,question_eurostar_cafe_the_range_of_drinks_on_offer,question_eurostar_cafe_the_prices_value_for_money_of_food_and_drinks,question_eurostar_cafe_the_product_availabilty,question_purchase_cafe,question_connecting_journey,question_main_trip_purpose,question_leisure_reason,service_id,trainset,equipment_type,train_service,route_type,origin_theoretical_time,destination_theoretical_time,restriction_open_Toilets,restriction_open_Air Conditioning,restriction_open_Refrigeration,restriction_open_Windows,restriction_open_WiFi,restriction_open_Heating,total restrictions,restriction_days_Toilets,restriction_days_Air Conditioning,restriction_days_Refrigeration,restriction_days_Windows,restriction_days_WiFi,restriction_days_Heating,longest restriction,pm_days_since_catering,pm_days_since_toilet,pm_days_since_climate,pm_days_since_interior,pm_days_since_reliability,pm_days_since_comms,pm_days_since_wifi,average days since last exams,pm_has_prior_catering,pm_has_prior_toilet,pm_has_prior_climate,pm_has_prior_interior,pm_has_prior_reliability,pm_has_prior_comms,pm_has_prior_wifi,cm_open_climate,cm_open_wifi,cm_open_interior,cm_open_catering,cm_open_toilet,cm_open_cleaning,total open faults,clean_score_routine,clean_hours_since_routine,clean_score_deep,clean_days_since_deep,last_clean_score,hours_since_last_clean,clean_has_prior_routine,clean_has_prior_deep,n_trainsets,early_journey_delay_minute,arrival_delay_minute,compensation_liability_evouchers,compensation_liability_cash,delay_cause_id,Arrival Delay,Cause Category_x,Cause Domain_x,Cause Responsibility_x,Departure Delay,Cause Category_y,Cause Domain_y,Cause Responsibility_y,Rame Number,Travel Number,Theoretical Rotation Time,Effective Rotation Time,Exceeded Rotation Time,met_departures,ordered_departures,unmet_departures,fleet_reliability,total_met_departures,total_ordered_departures,total_unmet_departures,total_fleet_reliability,Aggregated Delay,nps_category,Aggregated NPS
0,2024-10-01T14:58:17Z,Eurostar Standard,1.00,12.00,0.00,EUR,2.00,1.00,20250101,18:04,Amsterdam Centraal,5.00,None,London St Pancras Int'l,21.00,144.00,None,None,None,None,8.00,None,209,Blue,1.00,33.00,Small Business,6.00,Classique,3.00,9152.00,E320,2.00,1.00,2025-01-02T15:05:35Z,2025-01-02T15:02:05Z,5,2,4,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,5,<NA>,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,4,<NA>,<NA>,<NA>,4,5,['It was the most environmentally-friendly opt...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,3,Range of food/drink available at the Eurostar ...,<NA>,None,<NA>,None,United Kingdom,Between 26 - 34,4,4,3,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9152_20250101,4009+4010,E320,9152,Channel,2025-01-01 18:04:00+00:00,2025-01-01 23:20:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.00,26.00,26.00,128.00,232.00,2695.00,NaN,529.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,95.83,0.33,NaN,NaN,95.83,0.33,1,0,2,2.00,1.00,0.00,0.00,NaN,0.90,I6 - Traffic Regulation,Infrastructure Manager,External,0.00,I6 - Traffic Regulation,Infrastructure Manager,External,4010-4009,3.00,94.00,96.02,2.02,18.00,18.00,0.00,1.00,29.00,30.00,-1.00,0.97,0.90,neutral,0.00
1,2024-11-22T06:45:54Z,Eurostar Standard,1.00,2.00,0.00,GBP,2.00,7.00,20250101,12:56,London St Pancras Int'l,21.00,None,Brussels Midi / Zuid,9.00,115.00,None,Wifi was not working,None,None,10.00,None,201,Blue,1.00,65.00,None,NaN,Classique,3.00,9135.00,E300,1.00,1.00,2025-01-02T15:05:37Z,2025-01-02T15:02:15Z,5,1,5,4,4,4,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,3,<NA>,4,4,4,<NA>,<NA>,<NA>,<NA>,5,5,5,<NA>,<NA>,<NA>,5,5,['It was the cheapest option' 'It was the quic...,Eurostar would be my preferred choice,<NA>,<NA>,None,None,<NA>,<NA>,None,<NA>,None,4,At security (baggage checks/scanning),United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a main holiday,9135_20250101,3221+3222,E300,9135,Channel,2025-01-01 12:56:00+00:00,2025-01-01 13:57:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.00,3623.00,212.00,293.00,171.00,1904.00,NaN,1047.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,9.00,7.00,0.00,0.00,14.00,60.00,S1 - Passengers,Stations,Internal,7.70,S1 - Passengers,Stations,Internal,NaN,NaN,NaN,NaN,NaN,18.00,18.00,0.00,1.00,29.00,30.00,-1.00,0.97,67.70,promoter,0.50
2,2024-12-26T03:54:23Z,Eurostar Standard,1.00,10.00,0.00,EUR,2.00,2.00,20250101,19:34,Brussels Midi / Zuid,9.00,None,London St Pancras Int'l,21.00,134.00,None,The departing gate in London was very crowded ...,None,None,9.00,None,175,Blue,1.00,11.00,Small Business,6.00,Classique,3.00,9158.00,E320,2.00,2.00,2025-01-02T15:07:01Z,2025-01-02T15:04:05Z,5,4,2,5,5,4,4,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,4,<NA>,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,5,['It was the quickest option'\n 'It was the mo...,I would consider Eurostar along with other com...,5,3,None,None,<NA>,<NA>,The availability of toilet facilities on board,<NA>,None,<NA>,None,Belgium,Between 26 - 34,4,4,<NA>,<NA>,Promoter,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Visiting friends or relatives,None,9158_20250101,4033+4034,E320,9158,Channel,2025-01-01 19:34:00+00:00,2025-01-01 22:35:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.00,50.00,37.00,5.00,202.00,NaN,NaN,68.60,1,1,1,1,1,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,3.00,2.00,0.00,0.00,NaN,2.40,I4 - Infrastructure Fault,Infrastructure Manager,External,0.00,I4 - Infrastructure Fault,Infrastructure Manager,External,4033-4034,4.00,97.00,NaN,0.00,18.00,18.00,0.00,1.00,29.00,30.00,-1.00,0.97,2.40,promoter,0.50
4,2024-07-24T14:45:14Z,Eurostar Standard,1.00,12.00,0.00,GBP,2.00,1.00,20250101,14:42,London St Pancras Int'l,21.00,None,Paris Gare du Nord,25.00,54.00,None,I thought the facilities were great at Paris G...,None,None,8.00,None,309,Blue,1.00,33.00,None,NaN,Classique,3.00,9037.00,E320,2.00,2.00,2025-01-02T15:07:25Z,2025-01-02T15:02:15Z,4,3,5,5,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,4,4,<NA>,<NA>,<NA>,5,5,['It was the most environmentally-friendly opt...,Eurostar would be my preferred choice,5,<NA>,None,None,<NA>,<NA>,None,3,Signage for onward journey and/or connections ...,<NA>,None,United Kingdom,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a short break,9037_20250101,4021+4022,E320,9037,Channel,2025-01-01 14:42:00+00:00,2025-01-01 16:00:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.00,32.00,6.00,85.00,257.00,2793.00,NaN,538.33,1,1,1,1,1,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2,4.00,1.00,0.00,0.00,NaN,60.00,S1 - Passengers,Stations,Internal,4.30,S1 - Passengers,Stations,Internal,4021-4022,2.00,113.00,115.53,2.53,18.00,18.00,0.00,1.00,29.00,30.00,-1.00,0.97,64.30,neutral,0.50
5,2024-11-11T02:29:38Z,Eurostar Standard,1.00,6.00,0.00,EUR,1.00,33.00,20250101,10:25,Amsterdam Centraal,5.00,4|4,Paris Gare du Nord,25.00,63.00,None,"During and after the delay, I kept getting SMS...","Although there was a delay, which was dissatis...",None,8.00,None,304,Red,2.00,15.00,None,NaN,Classique,3.00,9427.00,TGH,6.00,1.00,2025-01-02T15:07:26Z,2025-01-02T15:02:21Z,5,3,4,3,5,5,5,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,<NA>,4,<NA>,<NA>,4,4,5,<NA>,1,<NA>,3,None,No,None,<NA>,English,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,5,5,5,5,5,5,4,['It was the quickest option'\n 'It was the mo...,Eurostar would be my preferred choice,5,<NA>,None,None,<NA>,<NA>,None,5,Disembarking the train,<NA>,None,The Netherlands,Between 18 - 25,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Regular commute,None,9427_20250101,4301,TGH,9427,Continental,2025-01-01 10:25:00+00:00,2025-01-01 13:50:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00,NaN,65.00,36.00,0,0,0,0,1,0,1,4.00,0.00,4.00,12.00,4.00,1.00,25.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0.00,33.00,0.00,0.00,60.00,33.80,Z1 - Weather related - Safety measures / Speed...,Force Majeure (No compensation),External,-0.80,None,None,None,NaN,NaN,NaN,NaN,NaN,11.00,12.00,-1.00,0.92,29.00,30.00,-1.00,0.97,33.00,neutral,0.20
6,2024-12-07T09:25:15Z,Eurostar Standard,1.00,6.00,0.00,EUR,2.00,0.00,20250101,10:25,Brussels Midi / Zuid,9.00,None,Paris Gare du Nord,25.00,95.00,None,None,None,None,8.00,None,182,Red,2.00,85.00,None,NaN,None,NaN,9427.00,TGH,6.00,1.00,2025-01-02T15:07:26Z,2025-01-02T15:04:23Z,5,1,4,5,4,4,4,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,No,None,<NA>,Dutch,4,4,<NA>,<NA>,<NA>,4,<NA>,<NA>,4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4,5,4,<NA>,<NA>,<NA>,3,4,['It was the quickest option'],I would consider Eurostar along with other com...,4,<NA>,None,Pre-departure announcements in the station,4,<NA>,None,<NA>,None,<NA>,None,Belgium,Between 18 - 25,<NA>,<NA>,<NA>,<NA>,Passive,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a short break,9427_20250101,4301,TGH,9427,Continental,2025-01-01 10:25:00+00:00,2025-01-01 13:50:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00,NaN,65.00,36.00,0,0,0,0,1,0,1,4.00,0.00,4.00,12.00,4.00,1.00,25.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0.00,33.00,0.00,0.00,60.00,33.80,Z1 - Weather related - Safety measures / Speed...,Force Majeure (No compensation),External,-0.80,None,None,None,NaN,NaN,NaN,NaN,NaN,11.00,12.00,-1.00,0.92,29.00,30.00,-1.00,0.97,33.00,neutral,0.20
7,2025-01-01T11:50:00Z,Eurostar Standard,1.00,5.00,0.00,EUR,1.00,29.00,20250101,19:25,Brussels Midi / Zuid,9.00,2|2,Paris Gare du Nord,25.00,109.00,None,Il faut que vous repreniez en main votre entre...,Vous faites payer ces billets des fortunes et ...,None,0.00,None,310,Red,2.00,44.00,Young VFR,8.00,Avantage,1.00,9481.00,TGH,6.00,9.00,2025-01-02T15:07:31Z,2025-01-02T15:02:21Z,4,3,2,1,3,3,3,2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1,<NA>,2,<NA>,<NA>,2,1,1,2,2,<NA>,2,None,No,None,<NA>,French,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3,3,3,3,3,3,3,3,3,3,3,3,3,<NA>,<NA>,<NA>,1,1,"[""Not my choice/Didn't have any other options""]",I would not consider Eurostar,3,2,None,None,<NA>,<NA>,None,<NA>,None,3,Train manager,Belgium,Between 35 - 49,<NA>,<NA>,<NA>,<NA>,Detractor,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,Leisure,Travel for a main holiday,9481_20250101,4538,TGH,9481,Continental,2025-01-01 19:25:00+00:00,2025-01-01 20:47:00+00:00,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.00,NaN,127.00,77.00,0,0,0,0,1,0,1,4.00,0.00,22.00,9.00,11.00,4.00,50.00,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,24.00,29.00,0.00,0.00,35.00,0.00,I6 - Traffic Regulation,Infrastructure Manager,External,0.00,I6 - Traffic Regulation,Infrastructure Manager,External,4538,4.00,47.00,54.88,7.87,11.00,12.00,-1.00,0.92,29.00,30.00,-1.00,0.97,0.00,detractor,-1.00

In [114]:
df.shape

(169480, 235)

In [113]:
df.to_parquet("Data/final_data.parquet", index=False)